//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonutShop
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DonutsShopEntities2 : DbContext
    {
        public DonutsShopEntities2()
            : base("name=DonutsShopEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Donut> Donuts { get; set; }
        public virtual DbSet<main> mains { get; set; }
        public virtual DbSet<Regtable> Regtables { get; set; }
        public virtual DbSet<UserTable> UserTables { get; set; }
    }
}
