//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DonutShop
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserTable
    {
        public int USER_id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<int> R_id { get; set; }
    }
}
